import {
  Transaction,
  TransactionType,
  TransactionCategory,
  TransactionPaymentMethod,
  DashboardData,
} from "@/app/_types/transaction";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-01-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "2",
    name: "Aluguel",
    type: TransactionType.EXPENSE,
    amount: 1200,
    category: TransactionCategory.HOUSING,
    date: new Date("2024-01-10"),
    paymentMethod: TransactionPaymentMethod.BANK_SLIP,
  },
  {
    id: "3",
    name: "Supermercado",
    type: TransactionType.EXPENSE,
    amount: 350.5,
    category: TransactionCategory.FOOD,
    date: new Date("2024-02-05"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "4",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-02-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "33",
    name: "Farmácia",
    type: TransactionType.EXPENSE,
    amount: 120,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-02-15"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "34",
    name: "Uber",
    type: TransactionType.EXPENSE,
    amount: 45,
    category: TransactionCategory.TRANSPORTATION,
    date: new Date("2024-02-20"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "5",
    name: "Transporte",
    type: TransactionType.EXPENSE,
    amount: 250,
    category: TransactionCategory.TRANSPORTATION,
    date: new Date("2024-03-08"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "6",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-03-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "35",
    name: "Almoço",
    type: TransactionType.EXPENSE,
    amount: 35,
    category: TransactionCategory.FOOD,
    date: new Date("2024-03-12"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "36",
    name: "Netflix",
    type: TransactionType.EXPENSE,
    amount: 45,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-03-15"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "7",
    name: "Lazer",
    type: TransactionType.EXPENSE,
    amount: 400,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-04-15"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "8",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-04-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "37",
    name: "Conta de água",
    type: TransactionType.EXPENSE,
    amount: 85,
    category: TransactionCategory.UTILITY,
    date: new Date("2024-04-10"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "38",
    name: "Padaria",
    type: TransactionType.EXPENSE,
    amount: 25,
    category: TransactionCategory.FOOD,
    date: new Date("2024-04-18"),
    paymentMethod: TransactionPaymentMethod.CASH,
  },
  {
    id: "9",
    name: "Consulta médica",
    type: TransactionType.EXPENSE,
    amount: 300,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-05-12"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "10",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-05-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "39",
    name: "Combustível",
    type: TransactionType.EXPENSE,
    amount: 280,
    category: TransactionCategory.TRANSPORTATION,
    date: new Date("2024-05-18"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "40",
    name: "Jantar",
    type: TransactionType.EXPENSE,
    amount: 180,
    category: TransactionCategory.FOOD,
    date: new Date("2024-05-25"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "11",
    name: "Conta de luz",
    type: TransactionType.EXPENSE,
    amount: 180,
    category: TransactionCategory.UTILITY,
    date: new Date("2024-06-10"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "12",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-06-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "41",
    name: "Cinema",
    type: TransactionType.EXPENSE,
    amount: 60,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-06-15"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "42",
    name: "Mercado",
    type: TransactionType.EXPENSE,
    amount: 420,
    category: TransactionCategory.FOOD,
    date: new Date("2024-06-22"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "13",
    name: "Investimento em ações",
    type: TransactionType.INVESTMENT,
    amount: 2000,
    category: TransactionCategory.OTHER,
    date: new Date("2024-07-15"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "14",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-07-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "43",
    name: "Academia",
    type: TransactionType.EXPENSE,
    amount: 120,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-07-08"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "44",
    name: "Aluguel",
    type: TransactionType.EXPENSE,
    amount: 1200,
    category: TransactionCategory.HOUSING,
    date: new Date("2024-07-10"),
    paymentMethod: TransactionPaymentMethod.BANK_SLIP,
  },
  {
    id: "15",
    name: "Curso online",
    type: TransactionType.EXPENSE,
    amount: 450,
    category: TransactionCategory.EDUCATION,
    date: new Date("2024-08-20"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "16",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-08-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "45",
    name: "Supermercado",
    type: TransactionType.EXPENSE,
    amount: 380,
    category: TransactionCategory.FOOD,
    date: new Date("2024-08-12"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "46",
    name: "Show",
    type: TransactionType.EXPENSE,
    amount: 250,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-08-25"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "17",
    name: "Restaurante",
    type: TransactionType.EXPENSE,
    amount: 150,
    category: TransactionCategory.FOOD,
    date: new Date("2024-09-18"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "18",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-09-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "47",
    name: "Farmácia",
    type: TransactionType.EXPENSE,
    amount: 95,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-09-10"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "48",
    name: "Uber",
    type: TransactionType.EXPENSE,
    amount: 35,
    category: TransactionCategory.TRANSPORTATION,
    date: new Date("2024-09-22"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "19",
    name: "Investimento em ações",
    type: TransactionType.INVESTMENT,
    amount: 3000,
    category: TransactionCategory.OTHER,
    date: new Date("2024-10-10"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "20",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-10-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "49",
    name: "Aluguel",
    type: TransactionType.EXPENSE,
    amount: 1200,
    category: TransactionCategory.HOUSING,
    date: new Date("2024-10-10"),
    paymentMethod: TransactionPaymentMethod.BANK_SLIP,
  },
  {
    id: "50",
    name: "Conta de internet",
    type: TransactionType.EXPENSE,
    amount: 120,
    category: TransactionCategory.UTILITY,
    date: new Date("2024-10-15"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "21",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-11-01"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "22",
    name: "Supermercado",
    type: TransactionType.EXPENSE,
    amount: 350.5,
    category: TransactionCategory.FOOD,
    date: new Date("2024-11-05"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "23",
    name: "Investimento em ações",
    type: TransactionType.INVESTMENT,
    amount: 50000,
    category: TransactionCategory.OTHER,
    date: new Date("2024-11-10"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "24",
    name: "Cinema",
    type: TransactionType.EXPENSE,
    amount: 50,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-11-12"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "25",
    name: "Consulta médica",
    type: TransactionType.EXPENSE,
    amount: 200,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-11-15"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "26",
    name: "Restaurante",
    type: TransactionType.EXPENSE,
    amount: 150,
    category: TransactionCategory.FOOD,
    date: new Date("2024-11-18"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "27",
    name: "Show",
    type: TransactionType.EXPENSE,
    amount: 300,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-11-20"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "28",
    name: "Freelance",
    type: TransactionType.DEPOSIT,
    amount: 1000,
    category: TransactionCategory.OTHER,
    date: new Date("2024-11-22"),
    paymentMethod: TransactionPaymentMethod.PIX,
  },
  {
    id: "29",
    name: "Academia",
    type: TransactionType.EXPENSE,
    amount: 100,
    category: TransactionCategory.HEALTH,
    date: new Date("2024-11-25"),
    paymentMethod: TransactionPaymentMethod.DEBIT_CARD,
  },
  {
    id: "30",
    name: "Viagem",
    type: TransactionType.EXPENSE,
    amount: 2000,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-11-28"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "31",
    name: "Salário",
    type: TransactionType.DEPOSIT,
    amount: 5000,
    category: TransactionCategory.SALARY,
    date: new Date("2024-12-05"),
    paymentMethod: TransactionPaymentMethod.BANK_TRANSFER,
  },
  {
    id: "32",
    name: "Presentes de Natal",
    type: TransactionType.EXPENSE,
    amount: 800,
    category: TransactionCategory.OTHER,
    date: new Date("2024-12-20"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "51",
    name: "Ceia de Natal",
    type: TransactionType.EXPENSE,
    amount: 450,
    category: TransactionCategory.FOOD,
    date: new Date("2024-12-24"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
  {
    id: "52",
    name: "Festa de Ano Novo",
    type: TransactionType.EXPENSE,
    amount: 300,
    category: TransactionCategory.ENTERTAINMENT,
    date: new Date("2024-12-31"),
    paymentMethod: TransactionPaymentMethod.CREDIT_CARD,
  },
];

// Lógica de negócio movida para app/_lib/services/dashboard.service.ts
